# -*- coding: utf-8 -*-
"""Streamlit.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10j-h2n3NOR54f5mobqmOPRN88YlWPFYG

#**Streamlit**
##Luis Pablo Padilla Barbosa
##A00572040
"""

import streamlit as st

st.write('Hello, *World!* :sunglasses:')